videoplatform/config/routes.rb
Videoplatform::Application.routes.draw do
  resources :users, :videos, :ratings, :courses
  resources :sessions, only: [:new, :create, :destroy]

  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

  match '/videos/new', to: 'videos#new'
  match '/courses/new', to: 'courses#new'
  match '/users/:id/history', to: 'users#history', as: 'history_user'

end

videoplatform/app/views/layouts/_admin_menu.html.erb
<li class="streep"></li>
<!-- Users -->
<li id="fat-menu" class="dropdown <%= 'active' if params[:controller] == 'users' && !current_user?(@user) %>">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
    Gebruikers <b class="caret"></b>
</a>
  <ul class="dropdown-menu">
    <li><%= link_to "Alle gebruikers weergeven", users_path %></li>
    <li><%= link_to "Gebruiker aanmaken", signup_path %></li>
  </ul>
</li>

<!-- Video's -->
<li id="fat-menu" class="dropdown <%= 'active' if params[:controller] == 'videos'  %>">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
    Video's <b class="caret"></b>
</a>
  <ul class="dropdown-menu">
    <li><%= link_to "Alle video's weergeven", videos_path %></li>
    <li><%= link_to "Nieuw video aanmaken", videos_new_path %></li>
  </ul>
</li>

<!-- Vakken -->
<li id="fat-menu" class="dropdown <%= 'active' if params[:controller] == 'courses'  %>">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
    Vakken <b class="caret"></b>
</a>
  <ul class="dropdown-menu">
    <li><%= link_to "Alle vakken weergeven", courses_path %></li>
    <li><%= link_to "Nieuw vak toevoegen", courses_new_path %></li>
  </ul>
</li>
<li class="streep"></li>

videoplatform/app/views/layouts/_footer.html.erb
<footer class="footer container">
  <small>
    &copy; 2012 Scrumbaggz
  </small>
  <nav>
    <ul>
      <li><%= link_to "Over",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://www.sbovhg.nl/index.php?pg=Nieuwsbrief&pid=107/">Niews</a></li>
    </ul>
  </nav>
</footer>

videoplatform/app/views/layouts/_header.html.erb
<header class="container">
	<div class="row navigation">
		<div class="span4"><%= link_to image_tag("logo.png", alt: "SBO Van Heuven Goedhart", class: "logo"), root_path %></div>
		<div class="span8">
			<div class="menu">
				<ul class="nav nav-pills">
				    <li class="<%= 'active' if params[:action] == 'home' && params[:controller] == 'static_pages'  %>">
				    	<%= link_to 'Home', root_path %>
				    </li>
				    <li class="<%= 'active' if params[:action] == 'help' && params[:controller] == 'static_pages'  %>">
				    	<%= link_to 'Help', help_path %>
				    </li>
				    <% if signed_in? %>
	            		
	            		<% if admin? %>
				            <%= render 'layouts/admin_menu' %>
				        <% end %>
				        <% if teacher? %>
				            <%= render 'layouts/teacher_menu' %>
				        <% end %>
	            		<li id="fat-menu" class="dropdown <%= 'active' if params[:action] == 'show' && params[:controller] == 'users' && current_user?(@user) %>">
		              		<a href="#" class="dropdown-toggle" data-toggle="dropdown">
		                	Account <b class="caret"></b>
		              	</a>
			              <ul class="dropdown-menu">
			                <li><%= link_to "Profiel", current_user %></li>
			                <li><%= link_to "Gegevens wijzigen", edit_user_path(current_user) %></li>
			                <li class="divider"></li>
			                <li>
			                  <%= link_to "Uitloggen", signout_path, method: "delete" %>
			                </li>
			              </ul>
			            </li>
		          	<% else %>
			            <li class="<%= 'active' if params[:action] == 'new' || 'create' && params[:controller] == 'sessions' %>">
			            	<%= link_to "Inloggen", signin_path %>
			            </li>
		          	<% end %>
		    	</ul>
	    	</div>
		</div>
	</div>
</header>

videoplatform/app/views/layouts/_kids_header.html.erb
<header class="container">
    <div class="row navigation">
        <div class="span4"><%= link_to image_tag("logo.png", alt: "SBO Van Heuven Goedhart", class: "logo"), root_path %></div>
        <div class="span8">
            <div class="menu" style="margin-top: 36px;">
                <ul class="nav nav-pills">
                    <li class="<%= 'active' if params[:action] == 'home' && params[:controller] == 'static_pages'  %>">
                        <%= link_to(root_path) do %>
                            <div class="nav-icon">
                                <ul>
                                    <li><%= image_tag("nav_icons/home.png", alt: "Home") %></li>
                                    <li>Home</li>
                                </ul>        
                            </div>
                        <% end %>
                    </li>
                    <li class="<%= 'active' if params[:action] == 'index' && params[:controller] == 'videos'  %>">
                        <%= link_to(videos_path) do %>
                            <div class="nav-icon">
                                <ul>
                                    <li><%= image_tag("nav_icons/video.png", alt: "Video's") %></li>
                                    <li>Alle video's</li>
                                </ul>        
                            </div>
                        <% end %>
                    </li>
                    <li class="<%= 'active' if params[:action] == 'index' && params[:controller] == 'courses'  %>">
                        <%= link_to(courses_path) do %>
                            <div class="nav-icon">
                                <ul>
                                    <li><%= image_tag("nav_icons/over-ons.png", alt: "Vakken") %></li>
                                    <li>Vakken</li>
                                </ul>        
                            </div>
                        <% end %>
                    </li>
                    <li class="<%= 'active' if params[:action] == 'history' && params[:controller] == 'users'  %>">
                        <%= link_to(history_user_path(current_user)) do %>
                            <div class="nav-icon">
                                <ul>
                                    <li><%= image_tag("nav_icons/geschiedenis.png", alt: "Bekeken video's") %></li>
                                    <li>Bekeken video's</li>
                                </ul>        
                            </div>
                        <% end %>
                    </li>
                    <li class="<%= 'active' if params[:action] == 'show' && params[:controller] == 'users'  %>">
                        <%= link_to(current_user) do %>
                            <div class="nav-icon">
                                <ul>
                                    <li><%= image_tag("nav_icons/profiel.png", alt: "Profiel") %></li>
                                    <li>Profiel</li>
                                </ul>        
                            </div>
                        <% end %>
                    </li>
                    <li class="<%= 'active' if params[:action] == 'help' && params[:controller] == 'static_pages'  %>">
                        <%= link_to(help_path) do %>
                            <div class="nav-icon">
                                <ul>
                                    <li><%= image_tag("nav_icons/help.png", alt: "Help") %></li>
                                    <li>Help</li>
                                </ul>        
                            </div>
                        <% end %>
                    </li>
                    <li>
                        <%= link_to(signout_path, method: "delete") do %>
                            <div class="nav-icon">
                                <ul>
                                    <li><%= image_tag("nav_icons/logout.png", alt: "Loguit") %></li>
                                    <li>Log Uit</li>
                                </ul>        
                            </div>
                        <% end %>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</header>

videoplatform/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

videoplatform/app/views/layouts/_teacher_menu.html.erb
<li class="streep"></li>
<!-- Users -->
<li id="fat-menu" class="dropdown <%= 'active' if params[:controller] == 'users' && !current_user?(@user) %>">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
    Gebruikers <b class="caret"></b>
</a>
  <ul class="dropdown-menu">
    <li><%= link_to "Alle gebruikers weergeven", users_path %></li>
  </ul>
</li>

<!-- Video's -->
<li id="fat-menu" class="dropdown <%= 'active' if params[:controller] == 'videos'  %>">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
    Video's <b class="caret"></b>
</a>
  <ul class="dropdown-menu">
    <li><%= link_to "Alle video's weergeven", videos_path %></li>
    <li><%= link_to "Nieuw video aanmaken", videos_new_path %></li>
  </ul>
</li>
<li class="streep"></li>

videoplatform/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= yield :scripts %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>    
  </head>
  <body>
    <% if signed_in? && !has_permissions? %>
      <%= render 'layouts/kids_header' %>
      <div class="container main">
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: "alert alert-#{key}") %>
        <% end %>
        <%= yield %>
      </div>
      <%= render 'layouts/footer' %>
    <% else %>
      <%= render 'layouts/header' %>
      <div class="container main">
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: "alert alert-#{key}") %>
        <% end %>
        <%= yield %>
      </div>
      <%= render 'layouts/footer' %>
    <% end %>
    <div class="container"><%= debug(params) if Rails.env.development? %></div>
  </body>
</html>