Mediatechnologie-Timeline/config/routes.rb
MTIdentity::Application.routes.draw do

  devise_for :users, :controllers => { :sessions => "sessions" }

  root to: "home#index"
  get "/" => "home#index"
  get "/contact" => "home#contact"
  get "/about" => "home#about"
  get "/college_year_overview" => "home#college_year_overview"
  get "/project_overview" => "home#project_overview"
  get "/timeline" => "static_pages#timeline"

  resources :home
  resources :users
  resources :projects

  resources :college_years do
    resources :projects do
      resources :groups
    end
  end

  namespace :dashboard do
    match "/" => "home#dashboard", :as => :dashboard

    resources :home
    resources :users
    resources :college_years
    resources :projects
    resources :groups
    resources :stickers
    resources :pictures
    resources :clients

    resources :college_years do
      resources :projects, :controller => "college_years/projects" do
        resources :groups, :controller => "projects/groups"
      end
    end

    resources :projects do
      resources :groups, :controller => "projects/groups"
      resources :stickers
    end

    resources :groups do
      resources :pictures
      member do
        get 'destroy_pictures'
      end
    end
  end

end

Mediatechnologie-Timeline/app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible :archived, :approved, :college_year_id, :description, :project_id, :title, :user_ids, :content, :client_ids
  has_and_belongs_to_many :users, :uniq => true
  belongs_to :project
  belongs_to :college_year
  has_many :pictures, :as => :imageable
  has_and_belongs_to_many :clients

  validates :title, :presence => true
  validates :description, :presence => true
  validates :content, :presence => true


end

Mediatechnologie-Timeline/app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :title, :description, :school_year, :preview, :remove_preview, :highlight, :college_year_ids, :client_ids
  has_and_belongs_to_many :college_years
  has_many :groups
  has_one :sticker

  mount_uploader :preview, BannerUploader

  validates :school_year, :presence => true

  YEARS = ["", "1e jaar", "2e jaar", "3e jaar", "4e jaar"]
  def school_year_display
    YEARS[school_year]
  end

end

Mediatechnologie-Timeline/app/controllers/dashboard/college_years/projects_controller.rb
class Dashboard::CollegeYears::ProjectsController < Dashboard::ProjectsController
  layout 'dashboard'
  before_filter :authenticate_user!
  before_filter :check_admin

  def index
    @college_year = CollegeYear.find(params[:college_year_id])
    @projects = @college_year.projects

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

   def show
    @college_year = CollegeYear.find(params[:college_year_id])
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  def new
    @college_year = CollegeYear.find(params[:college_year_id])
    @project = Project.new
    @college_years = CollegeYear.all
    @clients = Client.all
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  def edit
    @college_year = CollegeYear.find(params[:college_year_id])
    @project = Project.find(params[:id])
    @college_years = CollegeYear.all
    @clients = Client.all
  end

  def create
    @college_year = CollegeYear.find(params[:college_year_id])
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to dashboard_college_year_projects_path(@college_year), notice: 'Project was succesvol aangemaakt.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to dashboard_project_path(@project), notice: 'Project was succesvol bijgewerkt.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    @project.groups.destroy_all

    respond_to do |format|
      format.html { redirect_to dashboard_projects_url }
      format.json { head :no_content }
    end
  end
end

private
  def check_admin
    unless current_user.is_admin?
      redirect_to dashboard_dashboard_path, alert: 'U heeft hier niet de rechten voor.'
    end
  end

Mediatechnologie-Timeline/app/controllers/dashboard/groups_controller.rb
class Dashboard::GroupsController < ApplicationController
  layout 'dashboard'
  before_filter :authenticate_user!
  before_filter :is_authorized?, only: [:edit, :update, :destroy, :destroy_pictures]

  def index
    if current_user.is_admin?
      @groups = Group.all
    else
      @groups = current_user.groups
    end

    respond_to do |format|
      format.html
      format.json { render json: @groups }
    end
  end

  def show
    @group = Group.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render json: @group }
    end
  end

  def new
    @group = Group.new
    @users = User.all
    @college_years = CollegeYear.all
    @clients = Client.all

    respond_to do |format|
      format.html
      format.json { render json: @group }
    end
  end

  def edit
    @group = Group.find(params[:id])
    @projects = Project.all
    @college_years = CollegeYear.all
    @clients = Client.all
    @users = User.all
    @picture = @group.pictures.build
    @pictures = @group.pictures
  end

  def create
    @projects = Project.all
    @users = User.all
    @college_years = CollegeYear.all
    @clients = Client.all

    if params[:group][:college_year_id].include?('-')
      params[:group][:college_year_id] = CollegeYear.find_by_start_year(params[:group][:college_year_id][0,4]).id
    end
    @group = Group.new(params[:group])

    respond_to do |format|
      if @group.save
        # unless @group.users.include?(current_user) && !current_user.admin?
        #   @group.users << current_user
        # end
        format.html { redirect_to edit_dashboard_group_path(@group), notice: 'Team is succesvol aangemaakt.' }
        format.json { render json: @group, status: :created, location: @group }
      else
        format.html { render action: "new" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.json
  def update
    @projects = Project.all
    @users = User.all
    @college_years = CollegeYear.all
    @clients = Client.all

    @group = Group.find(params[:id])

    if params[:group][:college_year_id].include?('-')
      params[:group][:college_year_id] = CollegeYear.find_by_start_year(params[:group][:college_year_id][0,4]).id
    end
    respond_to do |format|
      if @group.update_attributes(params[:group])
        # unless @group.users.include?(current_user) && !current_user.admin?
        #   @group.users << current_user
        # end
        format.html { redirect_to dashboard_group_path(@group), notice: 'Team is succesvol bijgewerkt.' }
        format.json { head :no_content }
      else
        format.html { render action: "new" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to dashboard_groups_url }
      format.json { head :no_content }
    end
  end

  def destroy_pictures
    @group = Group.find(params[:id])
    @group.pictures.destroy_all

    respond_to do |format|
      format.html { redirect_to dashboard_groups_url }
      format.js
    end
  end
end

private
  def is_authorized?
    @group = Group.find(params[:id])
    unless current_user.is_admin? || @group.users.include?(current_user)
      redirect_to dashboard_groups_path, alert: 'U heeft hier niet de rechten voor.'
    end
  end

Mediatechnologie-Timeline/app/controllers/dashboard/projects/groups_controller.rb
class Dashboard::Projects::GroupsController < Dashboard::GroupsController
  layout 'dashboard'
  before_filter :authenticate_user!
  before_filter :get_college_year_project
  skip_before_filter :get_college_year_project, :only => [:update]
  before_filter :is_authorized?, only: [:edit, :update, :destroy, :destroy_pictures]

  def index
    @groups = @project.groups.where(:college_year_id => @college_year.id)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @groups }
    end
  end

  def show
    @group = Group.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @group }
    end
  end

  def new
    @group = Group.new
    @group.project_id = @project.id
    @group.college_year_id = @college_year.id

    @users = User.all
    @college_years = CollegeYear.all
    @clients = Client.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @group }
    end
  end

  def edit
    @group = Group.find(params[:id])

    @users = User.all
    @college_years = CollegeYear.all
    @clients = Client.all

    @picture = @group.pictures.build
    @pictures = @group.pictures
  end

  def create
    @users = User.all
    @college_years = CollegeYear.all
    @clients = Client.all

    if params[:group][:college_year_id].include?('-')
      params[:group][:college_year_id] = CollegeYear.find_by_start_year(params[:group][:college_year_id][0,4]).id
    end
    @group = Group.new(params[:group])

    respond_to do |format|
      if @group.save
        # unless @group.users.include?(current_user) && !current_user.admin?
        #   @group.users << current_user
        # end
        format.html { redirect_to edit_dashboard_college_year_project_group_path(@college_year, @project, @group), notice: 'Team was succesvol aangemaakt.' }
        format.json { render json: @group, status: :created, location: @group }
      else
        format.html { render action: "new" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @users = User.all
    @college_years = CollegeYear.all
    @clients = Client.all

    @group = Group.find(params[:id])

    if params[:group][:college_year_id].include?('-')
      params[:group][:college_year_id] = CollegeYear.find_by_start_year(params[:group][:college_year_id][0,4]).id
    end
    respond_to do |format|
      if @group.update_attributes(params[:group])
        # unless @group.users.include?(current_user) && !current_user.admin?
        #   @group.users << current_user
        # end
        format.html { redirect_to edit_dashboard_college_year_project_group_path(@group.college_year_id, @group.project_id, @group), notice: 'Team was succesvol bijgewerkt.' }
        format.json { head :no_content }
      else
        format.html { render action: "new" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to dashboard_groups_url }
      format.json { head :no_content }
    end
  end

  def destroy_pictures
    @group = Group.find(params[:id])
    @group.pictures.destroy_all

    respond_to do |format|
      format.html { redirect_to dashboard_project_cohort_groups_url(@project, @cohort)}
      format.js
    end
  end

end

private
  def get_college_year_project
    @college_year = CollegeYear.find(params[:college_year_id])
    @project = Project.find(params[:project_id])
  end

  def is_authorized?
    @group = Group.find(params[:id])
    unless current_user.is_admin? || @group.users.include?(current_user)
      redirect_to dashboard_groups_path, alert: 'U heeft hier niet de rechten voor.'
    end
  end

Mediatechnologie-Timeline/app/controllers/dashboard/projects_controller.rb
class Dashboard::ProjectsController < ApplicationController
  layout 'dashboard'
  before_filter :authenticate_user!
  before_filter :check_admin

  def index
    @college_years = CollegeYear.find(:all, :order => "start_year asc")
    @projects = Project.all

    respond_to do |format|
      format.html
      format.json { render json: @projects }
    end
  end

   def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @project }
    end
  end

  def new
    @project = Project.new
    @college_years = CollegeYear.all
    @clients = Client.all
    respond_to do |format|
      format.html
      format.json { render json: @project }
    end
  end

  def edit
    @project = Project.find(params[:id])
    @college_years = CollegeYear.all
    @clients = Client.all
  end

  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to dashboard_project_path(@project), notice: 'Project is succesvol aangemaakt.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to dashboard_project_path(@project), notice: 'Project is succesvol aangemaakt.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    @project.groups.destroy_all

    respond_to do |format|
      format.html { redirect_to dashboard_projects_url }
      format.json { head :no_content }
    end
  end
end

private
  def check_admin
    unless current_user.is_admin?
      redirect_to dashboard_dashboard_path, alert: 'U heeft hier niet de rechten voor.'
    end
  end

Mediatechnologie-Timeline/app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def show
    @college_year = CollegeYear.find(params[:college_year_id])
    @project = Project.find(params[:project_id])
    @group = Group.find(params[:id])

    respond_to do |format|
      format.html
      format.js
    end
  end
end

Mediatechnologie-Timeline/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
   def show
    @project = Project.find(params[:id])

    if params[:college_year_id].present?
      @college_year = CollegeYear.find(params[:college_year_id])
    else
      @college_year = @project.college_years.last
    end

    @groups = @project.groups.where(:college_year_id => @college_year)

    respond_to do |format|
      format.html
      format.js
    end
  end
end

Mediatechnologie-Timeline/app/helpers/groups_helper.rb
module GroupsHelper
end

Mediatechnologie-Timeline/app/helpers/projects_helper.rb
module ProjectsHelper
  def school_year_options
    years = []
    for i in 1..4
      years << ["#{i}e jaar", i]
    end
    years
  end
end

Mediatechnologie-Timeline/app/views/dashboard/projects/groups/_form.html.haml
= simple_form_for [:dashboard, :college_year, :project, @group] do |f|
  = f.error_notification
  %fieldset
    %legend Team
    .row
      .large-12.columns
        =f.input :title, required: true, label: 'Titel', placeholder: 'Naam van product/team'
    .row
      .large-12.columns
        =f.input :description, required: true, label: 'Beschrijving', placeholder: 'Korte Inleiding'
    .row
      .large-12.columns
        =f.input :content, required: false, label: 'Inhoud', placeholder: 'Uitgebreide beschrijving', input_html: {class: "ckeditor"}
    .row
      .large-12.columns
        =f.input :project_id, required: true, label: 'Project', collection: @college_years, as: :grouped_select, group_method: :projects , group_label_method: :years, label_method: :title, value_method: :id, prompt: "Selecteer een Project"
        =f.hidden_field :college_year_id, value: params[:college_year_id]
    .row
      .large-12.columns
        =f.association :users, collection: @users, value_method: :id, required: true, label: "Deelnemers", input_html: {class: "select2-input"}
    .row
      .large-6.columns
        =f.input :archived, required: false
      .large-6.columns
        =f.input :approved, required: false
    .row
      .large-12.columns
        - if params[:action] == "new"
          =f.button :submit, "Team aanmaken"
        - else
          =f.button :submit, "Wijzigingen opslaan"
        =link_to "Annuleren", :back, class: "button secondary"

:javascript
  $('#group_project_id').change(function(){
    var optgroup = $('#group_project_id :selected').parent().attr('label');
    $('#group_college_year_id').val(optgroup);
  });

Mediatechnologie-Timeline/app/views/dashboard/projects/groups/edit.html.haml
.row
  .large-12.columns
    %h2
      #{@college_year.years} / #{@project.title} / #{@group.title}

.row
  .large-12.columns
    %ul.breadcrumbs
      %li=link_to "Home", root_path
      %li=link_to "Dashboard", dashboard_dashboard_path
      %li=link_to "Collegejaren", dashboard_college_years_path
      %li=link_to @college_year.years, dashboard_college_year_path(@college_year)
      %li=link_to "Projecten", dashboard_college_year_projects_path(@college_year)
      %li=link_to @project.title, dashboard_college_year_project_path(@college_year, @project)
      %li=link_to "Teams", dashboard_college_year_project_groups_path(@college_year, @project)
      %li=link_to @group.title, dashboard_college_year_project_group_path(@college_year, @project, @group)
      %li.current=link_to "Bewerk team", edit_dashboard_college_year_project_group_path(@college_year, @project, @group)

.row
  .large-12.columns
    .section-container.auto{"data-section" => ""}
      %section
        %p.title{"data-section-title" => ""}
          %a{:href => "#panel1"} Gegevens
        .content{"data-section-content" => ""}
          = render 'form'
      %section
        %p.title{"data-section-title" => ""}
          %a{:href => "#panel2"} Afbeeldingen
        .content{"data-section-content" => ""}
          = render 'uploads'

Mediatechnologie-Timeline/app/views/dashboard/projects/groups/index.html.haml
.row
  .large-12.column
    %h2
      #{@college_year.years} / #{@project.title} : Teams
      =link_to new_dashboard_college_year_project_group_path(@college_year, @project), class: "btn-primary" do
        %i.icon-plus
        Nieuw team toevoegen

.row
  .large-12.columns
    %ul.breadcrumbs
      %li=link_to "Home", root_path
      %li=link_to "Dashboard", dashboard_dashboard_path
      %li=link_to "Collegejaren", dashboard_college_years_path
      %li=link_to @college_year.years, dashboard_college_year_path(@college_year)
      %li=link_to "Projecten", dashboard_college_year_projects_path(@college_year)
      %li=link_to @project.title, dashboard_college_year_project_path(@college_year, @project)
      %li.current=link_to "Teams", dashboard_college_year_project_groups_path(@college_year, @project)

/ .row
/   .large-12.column
/     %ul.navbar
/       %li
/         %a.active{href: "#"} Actief
/       %li
/         %a{href: "#"} Verborgen

.row
  .large-12.columns
    - if @groups.present?
      -@groups.each do |group|
        .row.card-info-row
          .large-2.column
            - if group.pictures.any?
              =image_tag group.pictures.first.image.thumb.url
            - else
              =image_tag "thumb_default_preview.jpg"
          .large-7.columns.info-description
            %h3 #{group.title}
            %p
              %strong Collegejaar
              = group.college_year.years unless group.college_year.nil?
              %strong Project
              = group.project.title unless group.project.nil?
            %p= group.description
          .large-3.columns.card-nested-list
            %ul
              - if group.users.any?
                - group.users.limit(5).each do |user|
                  %li=link_to user.name, dashboard_user_path(user)
              - else
                %li Nog geen gebruikers
        .row.buttons-row
          .large-12.columns
            %ul
              %li= link_to 'Bekijk', dashboard_college_year_project_group_path(@college_year, @project, group), class: "button small"
              %li= link_to 'Bewerk', edit_dashboard_college_year_project_group_path(@college_year, @project, group), class: "button small"
              %li= link_to 'Verwijder', dashboard_college_year_project_group_path(@college_year, @project, group), :method => :delete, :data => { :confirm => 'Weet je het zeker?' }, class: "button small alert"
    -else
      Nog geen teams! Klik
      =link_to " hier ", new_dashboard_college_year_project_group_path
      om een team toe te voegen.

Mediatechnologie-Timeline/app/views/dashboard/projects/groups/new.html.haml
.row
  .large-12.columns
    %h2
      #{@college_year.years} / #{@project.title}: Nieuw Team

.row
  .large-12.columns
    %ul.breadcrumbs
      %li=link_to "Home", root_path
      %li=link_to "Dashboard", dashboard_dashboard_path
      %li=link_to "Collegejaren", dashboard_college_years_path
      %li=link_to @college_year.years, dashboard_college_year_path(@college_year)
      %li=link_to "Projecten", dashboard_college_year_projects_path(@college_year)
      %li=link_to @project.title, dashboard_college_year_project_path(@college_year, @project)
      %li=link_to "Teams", dashboard_college_year_project_groups_path(@college_year, @project)
      %li.current=link_to "Nieuw Team", new_dashboard_college_year_project_group_path(@college_year, @project)

.row
  .large-12.columns
    = render 'form'

Mediatechnologie-Timeline/app/views/dashboard/projects/groups/show.html.haml
.row.card-detail
  .large-12.columns
    %h2
      #{@group.title} voorbeeld
      =link_to edit_dashboard_group_path(@group), class: "btn-primary" do
        %i.icon-edit
        Bewerk team

.row
  .large-12.columns
    %ul.breadcrumbs
      %li=link_to "Home", root_path
      %li=link_to "Dashboard", dashboard_dashboard_path
      %li=link_to "Collegejaren", dashboard_college_years_path
      %li=link_to @college_year.years, dashboard_college_year_path(@college_year)
      %li=link_to "Projecten", dashboard_college_year_projects_path(@college_year)
      %li=link_to @project.title, dashboard_college_year_project_path(@college_year, @project)
      %li=link_to "Teams", dashboard_college_year_project_groups_path(@college_year, @project)
      %li=link_to @group.title, dashboard_college_year_project_group_path(@college_year, @project, @group)

.row
  .large-12.columns
    %p=strip_tags @group.description

.full_width_gray
  .row.card-detail
    .large-12.columns
      %h4 Studenten die aan dit project werkten:
      %ul#users
        -@group.users.each_with_index do |user, index|
          -if index % 5 == 0
            %br
          =render :partial => "user", :locals => { :user => user }

.row.card-detail
  .large-12.columns
    .content=@group.content.html_safe

.row
  .large-12.columns
    %ul.large-block-grid-8.image-overview
      -@group.pictures.each do |pic|
        %li
          %a{href: "#{pic.image.url}", rel: "lightbox[pictures]"}
            = image_tag(pic.image.thumb.url)