Mediatechnologie-Timeline/config/routes.rb
MTIdentity::Application.routes.draw do

  devise_for :users, :controllers => { :sessions => "sessions" }

  root to: "home#index"
  get "/" => "home#index"
  get "/contact" => "home#contact"
  get "/about" => "home#about"
  get "/college_year_overview" => "home#college_year_overview"
  get "/project_overview" => "home#project_overview"
  get "/timeline" => "static_pages#timeline"

  resources :home
  resources :users
  resources :projects

  resources :college_years do
    resources :projects do
      resources :groups
    end
  end

  namespace :dashboard do
    match "/" => "home#dashboard", :as => :dashboard

    resources :home
    resources :users
    resources :college_years
    resources :projects
    resources :groups
    resources :stickers
    resources :pictures
    resources :clients

    resources :college_years do
      resources :projects, :controller => "college_years/projects" do
        resources :groups, :controller => "projects/groups"
      end
    end

    resources :projects do
      resources :groups, :controller => "projects/groups"
      resources :stickers
    end

    resources :groups do
      resources :pictures
      member do
        get 'destroy_pictures'
      end
    end
  end

end

Mediatechnologie-Timeline/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name, :admin, :student_number, :starting_year, :portfolio, :avatar, :remove_avatar, :description

  has_and_belongs_to_many :groups
  mount_uploader :avatar, AvatarUploader

  def is_admin?
    admin
  end

  def name
    "#{first_name} #{last_name}"
  end

  def owner?(project)
    if self.admin? || project.users.include?(self)
      return true
    else
      return false
    end
  end

  def starting_year_display
    starting_year.strftime("%Y")
  end

end

Mediatechnologie-Timeline/app/controllers/dashboard/clients_controller.rb
class Dashboard::ClientsController < ApplicationController
  layout 'dashboard'
  before_filter :authenticate_user!
  before_filter :check_admin

  def index
    @clients = Client.all

    respond_to do |format|
      format.html
      format.json { render json: @clients }
    end
  end

  def show
    @client = Client.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @client }
    end
  end

  def new
    @client = Client.new

    respond_to do |format|
      format.html
      format.json { render json: @client }
    end
  end

  def edit
    @client = Client.find(params[:id])
  end

  def create
    @client = Client.new(params[:client])

    respond_to do |format|
      if @client.save
        format.html { redirect_to dashboard_clients_path, notice: 'Opdrachtgever succesvol aangemaakt.' }
        format.json { render json: @client, status: :created, location: @client }
      else
        format.html { render action: "new" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @client = Client.find(params[:id])
    respond_to do |format|
      if @client.update_attributes(params[:client])
        format.html { redirect_to dashboard_client_path(@client), notice: 'Opdrachtgever succesvol bijgewerkt.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @client = Client.find(params[:id])
    @client.destroy

    respond_to do |format|
      format.html { redirect_to dashboard_clients_path }
      format.json { head :no_content }
    end
  end
end

private
  def check_admin
    unless current_user.is_admin?
      redirect_to dashboard_dashboard_path, alert: 'U heeft hier niet de rechten voor.'
    end
  end

Mediatechnologie-Timeline/app/controllers/dashboard/college_years/projects_controller.rb
class Dashboard::CollegeYears::ProjectsController < Dashboard::ProjectsController
  layout 'dashboard'
  before_filter :authenticate_user!
  before_filter :check_admin

  def index
    @college_year = CollegeYear.find(params[:college_year_id])
    @projects = @college_year.projects

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

   def show
    @college_year = CollegeYear.find(params[:college_year_id])
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  def new
    @college_year = CollegeYear.find(params[:college_year_id])
    @project = Project.new
    @college_years = CollegeYear.all
    @clients = Client.all
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  def edit
    @college_year = CollegeYear.find(params[:college_year_id])
    @project = Project.find(params[:id])
    @college_years = CollegeYear.all
    @clients = Client.all
  end

  def create
    @college_year = CollegeYear.find(params[:college_year_id])
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to dashboard_college_year_projects_path(@college_year), notice: 'Project was succesvol aangemaakt.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to dashboard_project_path(@project), notice: 'Project was succesvol bijgewerkt.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    @project.groups.destroy_all

    respond_to do |format|
      format.html { redirect_to dashboard_projects_url }
      format.json { head :no_content }
    end
  end
end

private
  def check_admin
    unless current_user.is_admin?
      redirect_to dashboard_dashboard_path, alert: 'U heeft hier niet de rechten voor.'
    end
  end

Mediatechnologie-Timeline/app/controllers/dashboard/college_years_controller.rb
class Dashboard::CollegeYearsController < ApplicationController
  layout 'dashboard'
  before_filter :authenticate_user!
  before_filter :check_admin

  def index
    @college_years = CollegeYear.find(:all, :order => "start_year desc")

    respond_to do |format|
      format.html
      format.json { render json: @college_years }
    end
  end

  def show
    @college_year = CollegeYear.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @college_year }
    end
  end

  def new
    @college_year = CollegeYear.new

    respond_to do |format|
      format.html
      format.json { render json: @college_year }
    end
  end

  def edit
    @college_year = CollegeYear.find(params[:id])
  end

  def create
    @college_year = CollegeYear.new(params[:college_year])

    respond_to do |format|
      if @college_year.save
        format.html { redirect_to dashboard_college_years_path, notice: 'Collegejaar succesvol aangemaakt.' }
        format.json { render json: @college_year, status: :created, location: @college_year }
      else
        format.html { render action: "new" }
        format.json { render json: @college_year.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @college_year = CollegeYear.find(params[:id])
    respond_to do |format|
      if @college_year.update_attributes(params[:college_year])
        format.html { redirect_to dashboard_college_year_path(@college_year), notice: 'Collegejaar succesvol bijgewerkt.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @college_year.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @college_year = CollegeYear.find(params[:id])
    @college_year.destroy

    respond_to do |format|
      format.html { redirect_to dashboard_college_years_path }
      format.json { head :no_content }
    end
  end
end

private
  def check_admin
    unless current_user.is_admin?
      redirect_to dashboard_dashboard_path, alert: 'U heeft hier niet de rechten voor.'
    end
  end

Mediatechnologie-Timeline/app/controllers/dashboard/groups_controller.rb
class Dashboard::GroupsController < ApplicationController
  layout 'dashboard'
  before_filter :authenticate_user!
  before_filter :is_authorized?, only: [:edit, :update, :destroy, :destroy_pictures]

  def index
    if current_user.is_admin?
      @groups = Group.all
    else
      @groups = current_user.groups
    end

    respond_to do |format|
      format.html
      format.json { render json: @groups }
    end
  end

  def show
    @group = Group.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render json: @group }
    end
  end

  def new
    @group = Group.new
    @users = User.all
    @college_years = CollegeYear.all
    @clients = Client.all

    respond_to do |format|
      format.html
      format.json { render json: @group }
    end
  end

  def edit
    @group = Group.find(params[:id])
    @projects = Project.all
    @college_years = CollegeYear.all
    @clients = Client.all
    @users = User.all
    @picture = @group.pictures.build
    @pictures = @group.pictures
  end

  def create
    @projects = Project.all
    @users = User.all
    @college_years = CollegeYear.all
    @clients = Client.all

    if params[:group][:college_year_id].include?('-')
      params[:group][:college_year_id] = CollegeYear.find_by_start_year(params[:group][:college_year_id][0,4]).id
    end
    @group = Group.new(params[:group])

    respond_to do |format|
      if @group.save
        # unless @group.users.include?(current_user) && !current_user.admin?
        #   @group.users << current_user
        # end
        format.html { redirect_to edit_dashboard_group_path(@group), notice: 'Team is succesvol aangemaakt.' }
        format.json { render json: @group, status: :created, location: @group }
      else
        format.html { render action: "new" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.json
  def update
    @projects = Project.all
    @users = User.all
    @college_years = CollegeYear.all
    @clients = Client.all

    @group = Group.find(params[:id])

    if params[:group][:college_year_id].include?('-')
      params[:group][:college_year_id] = CollegeYear.find_by_start_year(params[:group][:college_year_id][0,4]).id
    end
    respond_to do |format|
      if @group.update_attributes(params[:group])
        # unless @group.users.include?(current_user) && !current_user.admin?
        #   @group.users << current_user
        # end
        format.html { redirect_to dashboard_group_path(@group), notice: 'Team is succesvol bijgewerkt.' }
        format.json { head :no_content }
      else
        format.html { render action: "new" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to dashboard_groups_url }
      format.json { head :no_content }
    end
  end

  def destroy_pictures
    @group = Group.find(params[:id])
    @group.pictures.destroy_all

    respond_to do |format|
      format.html { redirect_to dashboard_groups_url }
      format.js
    end
  end
end

private
  def is_authorized?
    @group = Group.find(params[:id])
    unless current_user.is_admin? || @group.users.include?(current_user)
      redirect_to dashboard_groups_path, alert: 'U heeft hier niet de rechten voor.'
    end
  end

Mediatechnologie-Timeline/app/controllers/dashboard/home_controller.rb
class Dashboard::HomeController < ApplicationController
  layout 'dashboard'
  before_filter :authenticate_user!
  def dashboard
  end
end

Mediatechnologie-Timeline/app/controllers/dashboard/pictures_controller.rb
class Dashboard::PicturesController < ApplicationController
  layout 'dashboard'
  before_filter :authenticate_user!
  before_filter :is_authorized?, only: [:edit, :update, :destroy]

  def index
    @group = Group.find(params[:group_id])

    @pictures = @group.pictures

    respond_to do |format|
      format.html
      format.json { render json: @pictures }
    end
  end

  def show
    @picture = Picture.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @picture }
    end
  end

  def new
    @group = Group.find(params[:group_id])
    @picture = @group.pictures.build

    respond_to do |format|
      format.html
      format.json { render json: @picture }
    end
  end

  def edit
    @group = Group.find(params[:group_id])
    @picture = @group.pictures.find(params[:id])
    # @picture = Picture.find(params[:id])
  end

  def create
    p_attr = params[:picture]
    p_attr[:image] = params[:picture][:image].first if params[:picture][:image].class == Array

    if params[:group_id]
      @group = Group.find(params[:group_id])
      @picture = @group.pictures.build(p_attr)
    else
      @picture = Picture.new(p_attr)
    end

    if @picture.save
      respond_to do |format|
        format.html {
          render :json => [@picture.to_jq_upload].to_json,
          :content_type => 'text/html',
          :layout => false
        }
        format.json {
          render :json => {files: [@picture.to_jq_upload]}.to_json
        }
      end
    else
      render :json => [{:error => "custom_failure"}], :status => 304
    end
  end

  def update
    @group = Group.find(params[:group_id])

    @picture = @group.pictures.find(params[:id])

    respond_to do |format|
      if @picture.update_attributes(params[:picture])
        format.html { redirect_to edit_dashboard_group_path(@group), notice: 'Afbeelding is succesvol bijgewerkt.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @group = Group.find(params[:group_id])
    @picture = @group.pictures.find(params[:id])
    @picture.destroy

    respond_to do |format|
      format.html { redirect_to group_pictures_url }
      format.js
    end
  end
end

private
  def is_authorized?
    @group = Group.find(params[:id])
    unless current_user.is_admin? || @group.users.include?(current_user)
      redirect_to dashboard_groups_path, alert: 'U heeft hier niet de rechten voor.'
    end
  end

Mediatechnologie-Timeline/app/controllers/dashboard/projects_controller.rb
class Dashboard::ProjectsController < ApplicationController
  layout 'dashboard'
  before_filter :authenticate_user!
  before_filter :check_admin

  def index
    @college_years = CollegeYear.find(:all, :order => "start_year asc")
    @projects = Project.all

    respond_to do |format|
      format.html
      format.json { render json: @projects }
    end
  end

   def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @project }
    end
  end

  def new
    @project = Project.new
    @college_years = CollegeYear.all
    @clients = Client.all
    respond_to do |format|
      format.html
      format.json { render json: @project }
    end
  end

  def edit
    @project = Project.find(params[:id])
    @college_years = CollegeYear.all
    @clients = Client.all
  end

  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to dashboard_project_path(@project), notice: 'Project is succesvol aangemaakt.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to dashboard_project_path(@project), notice: 'Project is succesvol aangemaakt.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    @project.groups.destroy_all

    respond_to do |format|
      format.html { redirect_to dashboard_projects_url }
      format.json { head :no_content }
    end
  end
end

private
  def check_admin
    unless current_user.is_admin?
      redirect_to dashboard_dashboard_path, alert: 'U heeft hier niet de rechten voor.'
    end
  end

Mediatechnologie-Timeline/app/helpers/users_helper.rb
module UsersHelper
end

Mediatechnologie-Timeline/app/views/dashboard/users/_form.html.haml
= simple_form_for [:dashboard, @user] do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg
  .field_first_name
    =f.label "Voornaam"
    =f.text_field :first_name, :required => true
  .field_last_name
    =f.label "Achternaam"
    =f.text_field :last_name, :required => true
  .field_description.clearFix
    =f.label "Beschrijving"
    =f.text_area :description, :required => false
  .field_studentnumber
    =f.label "Studentnummer"
    =f.text_field :student_number, :required => true
  .field_starting_year
    =f.input :starting_year, required: true, label: 'Beginjaar', as: :date, start_year: Date.today.year - 5, end_year: Date.today.year + 3, discard_day: true, discard_month: true,  order: [:year], prompt: "Selecteer een beginjaar"
  .field_email
    =f.label "E-mail"
    =f.email_field :email, :required => true, id: "user_email_field"
  .field_portfolio.clearFix
    =f.label "Portfolio"
  .row.collapse
    .small-3.large-2.columns
      %span.prefix http://
    .small-9.large-10.columns
      =f.text_field :portfolio, :required => false
  -if params[:action] == "new"
    .row
      .large-6.columns
        =f.input :password, label: "Wachtwoord"
      .large-6.columns
        =f.input :password_confirmation, label: "Wachtwoord bevestigen"
  .field_picture
    =f.label "Foto"
    %p.upload-avatar Upload een spontane, representatieve foto hoe jij in het dagelijks leven bent!
    - if @user.avatar?
      =image_tag @user.avatar.profile.url
      %br
      %label
        = f.check_box :remove_avatar
        Verwijder foto
    =f.file_field :avatar
  .row
    .large-12.columns
      %hr/
      =f.input :admin
      %hr/

  .actions
    = f.submit 'Opslaan', class: "button"
    =link_to "Annuleren", :back, class: "button secondary"

:javascript
  $("#user_student_number").numeric();
  $("#user_student_number").keyup(function(){
    $("#user_email_field").val(this.value + "@hr.nl");
  });

Mediatechnologie-Timeline/app/views/dashboard/users/edit.html.haml
.row
  .large-12
    %h2 Profiel wijzigen
.row
  .large-12
    %ul.breadcrumbs
      %li=link_to "Home", root_path
      %li=link_to "Dashboard", dashboard_dashboard_path
      %li=link_to "Gebruikers", dashboard_users_path
      %li=link_to @user.name, @user
      %li.current=link_to "Gebruiker bewerken", edit_dashboard_user_path(@user)
.row
  .large-12
    = render 'form'

Mediatechnologie-Timeline/app/views/dashboard/users/index.html.haml
.row
  .large-12.columns
    %h2
      Gebruikers
      =link_to new_dashboard_user_path, class: "btn-primary" do
        %i.icon-plus
        Nieuwe gebruiker toevoegen

.row
  .large-12.columns
    %ul.breadcrumbs
      %li=link_to "Home", root_path
      %li=link_to "Dashboard", dashboard_dashboard_path
      %li.current=link_to "Gebruikers", dashboard_users_path

    %table#users_index.display
      %thead
        %tr
          %th Afbeelding
          %th Voornaam
          %th Achternaam
          %th E-mailadres
          %th
          %th
          %th
      %tbody
        - @users.each do |user|
          %tr
            - if user.avatar?
              /%td= cl_image_tag(user.avatar.path, { size: '50x50', crop: :fit})
              %td= image_tag(user.avatar.profile.url, :width => '50', :height => '50', class: 'avatar_overview')
            -else
              %td= image_tag("default_user.png", :width => '50', :height => '50')
            %td= user.first_name
            %td= user.last_name
            %td= user.email
            %td= link_to 'Bekijken', user
            %td= link_to 'Aanpassen', edit_dashboard_user_path(user)
            %td= link_to 'Verwijderen', dashboard_user_path(user), :method => :delete, :data => { :confirm => 'Wilt u deze gebruiker verwijderen?' }

:javascript
    $('#users_index').dataTable({
      sPaginationType: "full_numbers",
      bJQueryUI: true,
      oLanguage: {
        "sProcessing": "Bezig...",
        "sLengthMenu": "_MENU_ resultaten weergeven",
        "sZeroRecords": "Geen resultaten gevonden",
        "sInfo": "_START_ tot _END_ van _TOTAL_ resultaten",
        "sInfoEmpty": "Geen resultaten om weer te geven",
        "sInfoFiltered": " (gefilterd uit _MAX_ resultaten)",
        "sInfoPostFix": "",
        "sSearch": "Zoeken:",
        "sEmptyTable": "Geen resultaten aanwezig in de tabel",
        "sInfoThousands": ".",
        "sLoadingRecords": "Een moment geduld aub - bezig met laden...",
        "oPaginate": {
            "sFirst": "Eerste",
            "sLast": "Laatste",
            "sNext": "Volgende",
            "sPrevious": "Vorige"
        }
    }
  });

Mediatechnologie-Timeline/app/views/dashboard/users/new.html.haml
.row
  .large-12
    %h2 Nieuwe gebruiker
.row
  .large-12
    %ul.breadcrumbs
      %li=link_to "Home", root_path
      %li=link_to "Dashboard", dashboard_dashboard_path
      %li=link_to "Gebruikers", dashboard_users_path
      %li.current=link_to "Nieuwe gebruiker", new_dashboard_user_path
.row
  .large-12
    = render 'form'